services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGNAME}
    container_name: cont-name
    volumes:
      - ./postgres:/var/lib/postgresql/data